// Generated by https://quicktype.io

export interface CoffeeShopp {
  id:        number;
  name:      string;
  image:     string;
  price:     string;
  rating:    number;
  votes:     number;
  popular:   boolean;
  available: boolean;
}
